/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module car_speed_cntl(clock, keys, brake, accelerate, speed);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  input accelerate;
  input brake;
  input clock;
  input keys;
  wire [1:0] newspeed;
  output [1:0] speed;
  sky130_fd_sc_hd__nand2b_1 _22_ (
    .A_N(_12_),
    .B(_20_),
    .Y(_15_)
  );
  sky130_fd_sc_hd__nor2b_1 _23_ (
    .A(_21_),
    .B_N(_11_),
    .Y(_16_)
  );
  sky130_fd_sc_hd__nand2_1 _24_ (
    .A(_21_),
    .B(_12_),
    .Y(_17_)
  );
  sky130_fd_sc_hd__a21oi_1 _25_ (
    .A1(_21_),
    .A2(_12_),
    .B1(_11_),
    .Y(_13_)
  );
  sky130_fd_sc_hd__o22ai_1 _26_ (
    .A1(_15_),
    .A2(_16_),
    .B1(_13_),
    .B2(_20_),
    .Y(_18_)
  );
  sky130_fd_sc_hd__and3b_1 _27_ (
    .A_N(_12_),
    .B(_11_),
    .C(_20_),
    .X(_14_)
  );
  sky130_fd_sc_hd__o22a_1 _28_ (
    .A1(_20_),
    .A2(_17_),
    .B1(_14_),
    .B2(_21_),
    .X(_19_)
  );
  sky130_fd_sc_hd__dfrtp_1 _29_ (
    .CLK(clock),
    .D(newspeed[0]),
    .Q(speed[0]),
    .RESET_B(keys)
  );
  sky130_fd_sc_hd__dfrtp_1 _30_ (
    .CLK(clock),
    .D(newspeed[1]),
    .Q(speed[1]),
    .RESET_B(keys)
  );
  assign _21_ = speed[1];
  assign _20_ = speed[0];
  assign _12_ = brake;
  assign _11_ = accelerate;
  assign newspeed[0] = _18_;
  assign newspeed[1] = _19_;
endmodule
